version: '3.8'

services:

  http-one:
    image: nginx-one
    build:
      context: .
      dockerfile: Dockerfile.HttpA
    ports:
      - "8080:443"

  http-two:
    image: nginx-two
    build: 
      context: .
      dockerfile: Dockerfile.HttpB
    ports:
      - "8081:443"

  http-three:
    image: nginx-three
    build: 
      context: .
      dockerfile: Dockerfile.HttpC
    ports:
      - "8082:443"

  http-four:
    image: nginx-four
    build: 
      context: .
      dockerfile: Dockerfile.HttpD
    ports:
      - "8083:443"
